export const FONTS = {
  default: {
    name: 'Modern Sans',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  outfit: {
    name: 'Outfit (Clean & Bold)',
    fontFamily: "'Outfit', sans-serif",
  },
  playfair: {
    name: 'Editorial Serif',
    fontFamily: "'Playfair Display', Georgia, serif",
  },
  syne: {
    name: 'Creative Syne',
    fontFamily: "'Syne', sans-serif",
  },
  tajawal: {
    name: 'Tajawal (Arabic & Latin)',
    fontFamily: "'Tajawal', 'Plus Jakarta Sans', sans-serif",
  },
  mono: {
    name: 'Tech Mono',
    fontFamily: "'Space Mono', monospace",
  },
  luxury: {
    name: 'Cinzel Luxury',
    fontFamily: "'Cinzel', serif",
  },
}

export const BUTTON_STYLES = {
  rounded: {
    name: 'Rounded Card',
    borderRadius: 16,
    border: '1px solid rgba(0,0,0,0.06)',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
    effect: 'none',
  },
  pill: {
    name: 'Pill Shape',
    borderRadius: 9999,
    border: '1px solid rgba(0,0,0,0.06)',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
    effect: 'none',
  },
  glass: {
    name: 'Glassmorphism',
    borderRadius: 16,
    backdropFilter: 'blur(12px)',
    background: 'rgba(255, 255, 255, 0.25)',
    border: '1px solid rgba(255, 255, 255, 0.4)',
    boxShadow: '0 8px 32px 0 rgba(31, 38, 135, 0.12)',
    effect: 'glass',
  },
  glow: {
    name: 'Neon Glow',
    borderRadius: 16,
    border: '1.5px solid currentColor',
    boxShadow: '0 0 16px rgba(20, 184, 166, 0.35)',
    effect: 'glow',
  },
  shadow: {
    name: '3D Brutalist Pop',
    borderRadius: 14,
    border: '2px solid #0F172A',
    boxShadow: '4px 4px 0px #0F172A',
    effect: 'brutalist',
  },
  minimal: {
    name: 'Minimal Outline',
    borderRadius: 12,
    border: '1px solid currentColor',
    boxShadow: 'none',
    effect: 'minimal',
  },
}

export const THEMES = {
  default: {
    name: 'Clean Teal',
    category: 'Minimal',
    pageBg: '#F8FAFA',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    subTextColor: '#8A97A3',
    accent: '#14B8A6',
    swatch: 'linear-gradient(135deg, #F8FAFA, #E6F7F5)',
    buttonBg: 'rgba(20, 184, 166, 0.08)',
    buttonTextColor: '#0F172A',
    badge: 'Popular',
  },
  midnight: {
    name: 'Midnight Dark',
    category: 'Dark',
    pageBg: '#0B0F19',
    cardBg: '#111827',
    textColor: '#FFFFFF',
    subTextColor: '#9CA3AF',
    accent: '#2DD4BF',
    swatch: 'linear-gradient(135deg, #0B0F19, #1E293B)',
    buttonBg: 'rgba(255, 255, 255, 0.06)',
    buttonTextColor: '#FFFFFF',
  },
  aurora: {
    name: 'Aurora Glow',
    category: 'Animated Gradient',
    isAnimated: true,
    pageBg: 'linear-gradient(-45deg, #0f172a, #3b0764, #064e3b, #1e1b4b)',
    cardBg: 'rgba(15, 23, 42, 0.75)',
    backdrop: 'blur(20px)',
    textColor: '#FFFFFF',
    subTextColor: '#CBD5E1',
    accent: '#38BDF8',
    swatch: 'linear-gradient(135deg, #3b0764, #38BDF8)',
    buttonBg: 'rgba(255, 255, 255, 0.12)',
    buttonTextColor: '#FFFFFF',
    badge: 'Animated',
  },
  sunset: {
    name: 'Warm Sunset',
    category: 'Gradient',
    pageBg: 'linear-gradient(160deg, #FFF1EB, #ACE0F9)',
    cardBg: '#FFFFFF',
    textColor: '#1E293B',
    subTextColor: '#64748B',
    accent: '#F97316',
    swatch: 'linear-gradient(135deg, #FFF1EB, #F97316)',
    buttonBg: 'rgba(249, 115, 22, 0.08)',
    buttonTextColor: '#1E293B',
  },
  cyberpunk: {
    name: 'Neon Cyber',
    category: 'Dark',
    pageBg: '#09090B',
    cardBg: '#18181B',
    textColor: '#F4F4F5',
    subTextColor: '#A1A1AA',
    accent: '#EC4899',
    swatch: 'linear-gradient(135deg, #09090B, #EC4899)',
    buttonBg: 'rgba(236, 72, 153, 0.12)',
    buttonTextColor: '#FFFFFF',
    badge: 'Neon',
  },
  emerald: {
    name: 'Emerald Luxe',
    category: 'Luxury',
    pageBg: 'linear-gradient(160deg, #022C22, #064E3B)',
    cardBg: 'rgba(6, 78, 59, 0.65)',
    backdrop: 'blur(16px)',
    textColor: '#ECFDF5',
    subTextColor: '#A7F3D0',
    accent: '#34D399',
    swatch: 'linear-gradient(135deg, #022C22, #34D399)',
    buttonBg: 'rgba(52, 211, 153, 0.15)',
    buttonTextColor: '#ECFDF5',
  },
  lavender: {
    name: 'Soft Lavender',
    category: 'Pastel',
    pageBg: 'linear-gradient(160deg, #F5F3FF, #EDE9FE)',
    cardBg: '#FFFFFF',
    textColor: '#4C1D95',
    subTextColor: '#7C3AED',
    accent: '#8B5CF6',
    swatch: 'linear-gradient(135deg, #F5F3FF, #8B5CF6)',
    buttonBg: 'rgba(139, 92, 246, 0.08)',
    buttonTextColor: '#4C1D95',
  },
  cosmic: {
    name: 'Cosmic Violet',
    category: 'Animated Gradient',
    isAnimated: true,
    pageBg: 'linear-gradient(-45deg, #1E1B4B, #4C1D95, #831843, #0F172A)',
    cardBg: 'rgba(30, 27, 75, 0.75)',
    backdrop: 'blur(20px)',
    textColor: '#FFFFFF',
    subTextColor: '#E0E7FF',
    accent: '#C084FC',
    swatch: 'linear-gradient(135deg, #4C1D95, #C084FC)',
    buttonBg: 'rgba(192, 132, 252, 0.15)',
    buttonTextColor: '#FFFFFF',
    badge: 'Animated',
  },
  gold: {
    name: 'Golden Elegance',
    category: 'Luxury',
    pageBg: '#121212',
    cardBg: '#1C1917',
    textColor: '#FEF08A',
    subTextColor: '#CA8A04',
    accent: '#EAB308',
    swatch: 'linear-gradient(135deg, #121212, #EAB308)',
    buttonBg: 'rgba(234, 179, 8, 0.12)',
    buttonTextColor: '#FEF08A',
  },
  ocean: {
    name: 'Ocean Breeze',
    category: 'Gradient',
    pageBg: 'linear-gradient(160deg, #E0F2FE, #BAE6FD)',
    cardBg: '#FFFFFF',
    textColor: '#0C4A6E',
    subTextColor: '#0284C7',
    accent: '#0284C7',
    swatch: 'linear-gradient(135deg, #E0F2FE, #0284C7)',
    buttonBg: 'rgba(2, 132, 199, 0.08)',
    buttonTextColor: '#0C4A6E',
  },
  brutalist: {
    name: 'Tokyo Neo-Brutalist',
    category: 'Creative',
    pageBg: '#FEF08A',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    subTextColor: '#475569',
    accent: '#F43F5E',
    swatch: 'linear-gradient(135deg, #FEF08A, #F43F5E)',
    buttonBg: '#FFFFFF',
    buttonTextColor: '#0F172A',
    badge: 'Bold',
  },
  mono: {
    name: 'Minimal Mono',
    category: 'Minimal',
    pageBg: '#F4F4F5',
    cardBg: '#FFFFFF',
    textColor: '#18181B',
    subTextColor: '#71717A',
    accent: '#27272A',
    swatch: 'linear-gradient(135deg, #F4F4F5, #27272A)',
    buttonBg: 'rgba(39, 39, 42, 0.06)',
    buttonTextColor: '#18181B',
  },
}

export function getTheme(key) {
  return THEMES[key] || THEMES.default
}

export function getFont(key) {
  return FONTS[key] || FONTS.default
}

export function getButtonStyle(key) {
  return BUTTON_STYLES[key] || BUTTON_STYLES.rounded
}
